language: node_js
os:
    - linux
    - windows
node_js:
    - "stable"
    - "8.9.3"
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
